### ISSUE TITLE
Python教程XML一节是否应当修改？

### ISSUE THREAD

**Issue by Clayblockunova** [michaelliao/liaoxuefeng.com#1]
Python教程XML一节练习部分在运行时存在错误：
`urllib.error.URLError: <urlopen error unknown url type: https>`
另一方面，根据我在网上搜索到的信息，Yahoo天气API目前（2024年7月21日）URI已发生变更，使用时需要预先授权，数据为JSON格式，且无法在中国大陆境内使用。这一问题会如何处置？

**Comment by michaelliao** [comment]
https://liaoxuefeng.com/books/python/built-in-modules/xml/index.html

**Comment by Clayblockunova** [comment]
URL lib一节也需要类似的修改吗？分布于其他各章节的过时语法是否需要清理？
