### ISSUE TITLE
新主题下JQuery高亮代码失效

### ISSUE THREAD

**Issue by Clayblockunova** [michaelliao/liaoxuefeng.com#2]
在站点更换新主题后，JQuery选择器练习部分的高亮代码失去了原有效果。是不是因为背景色被主题设为只读的缘故？

**Comment by michaelliao** [comment]
这不是高亮吗？
![image](https://github.com/user-attachments/assets/a3a5ef4e-ea67-4023-9b50-8b2bc07df31e)

**Comment by Clayblockunova** [comment]
抱歉，当时按id查找的时候忘了打井号了，是我的问题。

**Comment by Clayblockunova** [comment]
抱歉，当时按id查找的时候忘了打井号了，是我的问题。
